param([Parameter(Mandatory=$true)][string]$Milestone)

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path $PSScriptRoot -Parent)

if (-not (Test-Path '.git')) {
    Write-Host "BLOCKED: not a git repo"
    exit 1
}

$branch = (& git rev-parse --abbrev-ref HEAD).Trim()
$remote = (& git remote get-url origin 2>$null)

if (-not $remote) {
    Write-Host "BLOCKED: no origin"
    exit 1
}

New-Item -ItemType Directory -Force -Path '.evidence' | Out-Null

$stamp = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
$log = ".evidence\${Milestone}_$stamp.log"

& python scripts\validate_phase.py --milestone $Milestone 2>&1 |
    Tee-Object -FilePath $log

if ($LASTEXITCODE -ne 0) {
    Write-Host "RESULT: BLOCKED - validation"
    exit 1
}

# Preserve the caller's intentionally staged files.
# Do NOT sweep backend/scripts/project directories.
$diff = (& git diff --cached -U0) -join "`n"

if (-not $diff) {
    Write-Host "RESULT: BLOCKED - nothing staged"
    exit 1
}

$pats = @(
    'sk-[A-Za-z0-9]{20,}',
    'Bearer\s+[A-Za-z0-9._\-]{20,}',
    '-----BEGIN [A-Z ]+PRIVATE KEY-----',
    'SECURE_1PSID'
)

foreach ($p in $pats) {
    if ($diff -match $p) {
        Write-Host "RESULT: BLOCKED - secret $p"
        exit 1
    }
}

# Add only the validation evidence generated by this run.
git add -- $log

# Re-check staged content.
& git diff --cached --check

if ($LASTEXITCODE -ne 0) {
    Write-Host "RESULT: BLOCKED - staged whitespace"
    exit 1
}

Write-Host ""
Write-Host "=== STAGED MILESTONE CONTENT ==="
git diff --cached --name-status
git diff --cached --stat

$msg = "feat(${Milestone}): milestone checkpoint`n`nMilestone: $Milestone`nValidation: PASS`nEvidence: $log"

& git commit -m $msg

if ($LASTEXITCODE -ne 0) {
    Write-Host "RESULT: BLOCKED - commit"
    exit 1
}

& git push origin $branch

if ($LASTEXITCODE -ne 0) {
    Write-Host "RESULT: BLOCKED - push"
    exit 1
}

$sha = (& git rev-parse HEAD).Trim()
$ls = (& git ls-remote origin "refs/heads/$branch") -join "`n"

if ($ls -notmatch [regex]::Escape($sha)) {
    Write-Host "RESULT: BLOCKED - remote verify"
    exit 1
}

Write-Host "============================================"
Write-Host "MILESTONE: $Milestone"
Write-Host "RESULT: PASS"
Write-Host "COMMIT: $sha"
Write-Host "BRANCH: $branch"
Write-Host "============================================"
